FROM node:19-alpine
ENV PATH /app/node_modules/.bin:$PATH
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install 
RUN npm install react-scripts@5.0.1 -g
COPY . ./
# RUN npm run build

# # production environment
# FROM nginx:stable-alpine
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
# CMD ["nodemon", "--exec", "npm", "start"]
CMD ["npm", "start"]
