# Generated by Django 4.1.7 on 2023-02-25 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='пользователи')),
            ],
            options={
                'verbose_name': 'беседа',
                'verbose_name_plural': 'беседы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'не доставлен'), (1, 'доставлен'), (2, 'не прочитан'), (3, 'прочитан')], default=0, verbose_name='статус')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='вложенный файл')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='дата доставки')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='дата прочтения')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.room', verbose_name='беседа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('-create_date',),
            },
        ),
    ]
