# Generated by Django 4.1.7 on 2024-07-11 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='название')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('actives', models.ManyToManyField(related_name='actives', to=settings.AUTH_USER_MODEL, verbose_name='активные пользователи')),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='администраторы')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='пользователи')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'активный'), (2, 'удален')], default=1, verbose_name='состояние')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='вложенный файл')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='дата изменения')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
                ('to_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chat', verbose_name='получатель: чат')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='получатель: пользователь')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateTimeField(auto_now_add=True, verbose_name='дата прочтения сообщения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='chats.message', verbose_name='сообщение')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'читатель',
                'verbose_name_plural': 'читатели',
                'ordering': ('-read_date',),
            },
        ),
    ]
